#!/bin/bash
# Requirements: bash, git, pacman

cd "/home/$USER/"

mkdir "/home/$USER/.local/"
mkdir "/home/$USER/.local/etc/"
mkdir "/home/$USER/.local/lib/"
mkdir "/home/$USER/.local/share/"
mkdir "/home/$USER/.local/src/"
mkdir "/home/$USER/.local/bin/"
mkdir "/home/$USER/documents/"
mkdir "/home/$USER/downloads/"
mkdir "/home/$USER/pictures/"
mkdir "/home/$USER/pictures/wallpapers/"
mkdir "/home/$USER/videos/"
mkdir "/home/$USER/projects/"
mkdir "/home/$USER/games/"

# Get setbg
git clone https://github.com/fatpancakes/bin.git
mv "bin/setbg" "/home/$USER/.local/bin/"
chmod +x "/home/$USER/.local/bin/setbg"
rm -rf bin

# Get qtile config and .xinitrc
git clone https://github.com/fatpancakes/dotfiles.git
mv "dotfiles/.xinitrc" "/home/$USER/"
mkdir "/home/$USER/.config/"
mkdir "/home/$USER/.config/qtile/"
mv "dotfiles/.config/qtile/config.py" "/home/$USER/.config/qtile/"

mv "kbase/default_wallpaper.jpg" "/home/$USER/pictures/wallpapers/"

sudo pacman -S --needed base-devel
git clone https://aur.archlinux.org/paru.git
cd paru
makepkg -si
cd ..
rm -rf paru

paru -S xorg-server xorg-xinit xorg-xwininfo xorg-font-util xdotoool xclip xwallpaper xcompmgr arandr neovim mpv man zathura zathura-pdf-mupdf brave-bin python python-pip wget ttf-ms-fonts transmission-cli openvpn cheat-bin dmenu sxiv qtile


setbg "/home/$USER/pictures/wallpapers/default_wallpaper.jpg"
