#!/bin/bash
# Requirements: bash, git, pacman

cd "/home/$USER/"

# Get qtile config and .xinitrc
git clone https://github.com/fatpancakes/dotfiles.git
mv "dotfiles/.xinitrc" "/home/$USER/"
mkdir "/home/$USER/.config/qtile/"
mv "dotfiles/config.py" "/home/$USER/.config/qtile/"

sudo pacman -S --needed --noconfirm base-devel
git clone https://aur.archlinux.org/paru.git
cd paru
makepkg -si --noconfirm
cd ..
rm -rf paru

paru -S xorg-server xorg-xinit xorg-xwininfo xorg-font-util xdotool xclip xwallpaper xcompmgr arandr neovim mpv man zathura zathura-pdf-mupdf python python-pip wget  transmission-cli openvpn  dmenu sxiv qtile kitty gnu-free-fonts --noconfirm

paru -S brave-bin --noconfirm
